project:
  type: website

website:
  title: "Mon site"
  navbar:
    left:
      - text: "Accueil"
        file: index.qmd
      - text: "Articles"
        file: article.qmd
      - text: "Scraping"
        file: scrap.qmd
      - text: "API"
        file: api.qmd
      - text: "Quarto"
        file: quarto.qmd
      - text: "Parquet"
        file: parquet.qmd
      - text: "Zotero"
        file: zotero.qmd

format:
  html:
    theme: cosmo
    toc: true



