project:
  type: website

website:
  title: "Kantiles - Supports de Formation"
  navbar:
    left:
      - text: "Accueil"
        menu:
          - text: "Accueil"
            file: index.qmd
          - text: "Stage mars-juillet 2025"
            file: cr_stage.qmd
          - text: "Article : Kantiles fête ses 10 ans"
            file: article.qmd
          - text: "Blason Kantiles"
            file: blason.qmd

      - text: "Scraping"
        file: scrap.qmd

      - text: "API"
        file: api.qmd

      - text: "Format"
        menu:
          - text: "Quarto"
            file: quarto.qmd
          - text: "Parquet"
            file: parquet.qmd
          - text: "Lire des Excels moches"
            file: fichier_moches.qmd

      - text: "Zotero"
        file: zotero.qmd

      - text: "Cartographie"
        file: cartographie.qmd

      - text: "Packages R"
        menu:
          - text: "Créer un package R"
            file: package.qmd
          - text: "Tester ses fonctions dans un package R"
            file: test_package.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

